version: "3.8"

services:
  frontend:
    image: terramino-frontend:latest
    ports:
      - "8081:8081"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  backend:
    image: terramino-backend:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TERRAMINO_PORT: 8080
    ports:
      - "8080:8080"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  redis_data:

